source 'https://rubygems.org'

gem 'github-pages', 32
group :development do
    gem 'guard'
    gem 'guard-jekyll'
    gem 'guard-jekyll-plus'
    gem 'guard-livereload'
    gem 'jekyll-github-metadata'
end
