jsbuild:
  jquery:
    - deprecated
    - effects
  jqueryui:
    - widget
    - core
    - position
    - autocomplete
  bootstrap:
    - affix
    - transition
    - collapse
    - dropdown
    - modal
    - tooltip
    - popover
    - tab
    - alert
  lodash: auto # auto|full

target: dev

targets:
  dev:
    stubs: src/stubs
    dest: dev
    type: dev
    site: {}
    nav:
      pre: ''
      ext: .html

  dist:
    stubs: src/stubs
    dest: dist
    type: dist
    site: {}
    nav:
      pre: ''
      ext: .html
