host:
  port: 9009
  name: 0.0.0.0

jsbuild:
  jquery:
    - deprecated
    - effects
  jqueryui:
    - widget
  bootstrap:
    - transition
    - collapse
    - dropdown
    - modal
    - tooltip
    - popover
    - tab

# types: dev, dist-html, dist-jekyll
builds:
  - name: dist_local
    dir: dist
    type: dist-html
    host:
      name: dev2.radic.nl
      port: 80
      protocol: http
    url: http://dev2.radic.nl
    git: false

  - name: dist_ghpages
    type: dist-jekyll
    host:
      name: packadic.radic.nl
      port: 80
      protocol: http
    url: http://packadic.radic.nl
    git:
      repo: packadic/packadic.github.io
      branch: master
