jsbuild:
  jquery:
    - deprecated
    - effects
  jqueryui:
    - widget
  bootstrap:
    - transition
    - collapse
    - dropdown
    - modal
    - tooltip
    - popover
    - tab

builders:
  base:
    builder: base # which of the builders in grunt/builders to use
    dest: dev     # any folder, relative to project root
    type: dev     # dist|dev. dist will minify, optimize and complement tasks with extra stuff (time consuming stuff)
    minify:
      html: false
      js: false
      css: false
      images: false
    host:
      name: dev2.radic.nl
      port: 80
      protocol: http
    url: http://dev2.radic.nl
    git: false

  jekyll:
    builder: jekyll # which of the builders in grunt/builders to use
    dest: jekyll     # any folder, relative to project root
    type: dev     # dist|dev. dist will minify, optimize and complement tasks with extra stuff (time consuming stuff)
    minify:
      html: false
      js: false
      css: false
      images: false
    host:
      name: dev2.radic.nl
      port: 80
      protocol: http
    url: http://dev2.radic.nl
    git: false

paths:
  stubs: src/stubs
