#!/usr/bin/env node
var requirejs = require('requirejs'),
    util = require('util'),
    _ = require('lodash');

function dump(val){
    process.stdout.write(util.inspect(val, { hidden: true, colors: true, depth: 5}));
}

function getMainConfig(){
    GLOBAL.window = {};
    require('./src/scripts/init');
    var rjsConfig = {};
    Object.keys(GLOBAL.window.packadic.config.requireJS).forEach(function( k ){
        rjsConfig[ k ] = GLOBAL.window.packadic.config.requireJS[ k ];
    });
    delete GLOBAL.window;
    return rjsConfig;
}
var rconfig = getMainConfig();
var config = {
    paths: rconfig.paths,
    shim: rconfig.shim,
    baseUrl                : "dev/assets/scripts",
    optimizeCss            : false,
    modules                : [
        {name: "ace-editor"},
        {
            name: 'boot', include: [
                'jquery', 'plugins/async', 'autoloader', 'string', 'jade', 'code-mirror',
                'plugins/cookie', 'theme', 'theme/sidebar', 'config',
                'templates/sidebar','templates/alert','templates/box','templates/table',
                'eventer', 'plugins/bs-material-ripples', 'storage', 'json',
                'fn/defined', 'fn/default', 'fn/cre', 'Q'
            ]
        },
        {
            name: 'demo',
            exclude: ['boot'],
            include: ['demo/show-html', 'demo/show-class', 'demo/forms', 'demo/button-icon-showcase']
        },
        {
            name: 'datatable',
            exclude: ['demo', 'boot'],
            include: ['datatables', 'vendor/dataTables.bootstrap']
        }
    ],
    dir                    : "dist/assets/scripts2",
    uglify: "none",
    skipDirOptimize: true,
    preserveLicenseComments: false,
    removeCombined         : true,
    optimizeAllPluginResources: true
};
delete config.paths['plugins/select2css'];
delete config.paths['plugins/highlightjscss'];
delete config.shim['plugins/select2'];
delete config.shim['plugins/highlightjs'];



dump(config);
requirejs.optimize(config, function(asdf){
    console.log(asdf);
});
